### ISSUE TITLE
Site review

### ISSUE THREAD

**Issue by kdruken** [ACCESS-Hive/access-hive.github.io#70]
Site review before launch to check text, look/feel, navigation, etc.

**Comment by ccarouge** [comment]
Summary of feedback:

- [ ] Merge "ACCESS-Hive" and "About" tabs. Maybe add a "Contributions" tab for the contribution guidelines. (#127, #43 )
- [ ] "About" page: refine the definition of "supported", "recommended" and "community" links (#114)
- [ ] Should we explain where the documentation supported by ACCESS-NRI will reside in the "ACCESS-Hive"/"About" page? (#127)
- [ ] "Components" tab: in the overall table, change the icons to the icons with the names of the components. (#127)
- [ ] Add information about reference model papers for each model components. (SAC)
- [ ] Add "ice sheets" as a component: 1) create icon, 2) contact Ben Galton-Fenzi or Felicity McCormack for content. (SAC)
- [ ] "Events" tab: 1) Move the events to the spash screen together and add a "past events" page. 2) Link with the website? Should we also have an event calendar on the website? (#120, #127, #43)
- [ ] "how to contribute" guide: 1) remove text about assigning issues, only people with write access can do that. (#119)
- [ ] Look of the site: 1) What logo to use in the top left of the header. (#68)
- [ ] What do we do with orphaned documentation? (#124)
- [ ] Why is the site not indexed by search sites?
- [ ] Review the permissions on the organisation and repository as well as teams. Should the organisation's members have write access? Do we need other teams? (#65)
- [ ] create reusable actions from the preview workflows so we can reuse them for other mkdocs sites.

**Comment by rbeucher** [comment]
The indexing of the website is a bit of a mystery to me. I did request the site to be indexed from the google search console. Something to investigate more.

**Comment by ccarouge** [comment]
We also need to decide on:

- [ ] communication for the launch
- [ ] links between ACCESS-Hive and the ACCESS-NRI website and other resources (e.g. a permanent link from the newsletter?)

**Comment by aidanheerdegen** [comment]
- [ ] Inconsistent use of hyphen in ACCESS-Hive

```
$ grep -ir 'ACCESS Hive' *
README.md:[![ACCESS Hive Badge](docs/assets/badge.svg)](https://access-hive.github.io/ACCESS-Hive/)
docs/call_contribute.md:    The ACCESS Hive is a community resource that is a work in progress. Can you help to add content to this page? We’d love to receive your contribution. See our [contributing guidelines](https://access-hive.github.io/ACCESS-Hive/about/contribute) for details of how to provide content. You can also [open an issue](https://github.com/ACCESS-Hive/ACCESS-Hive/issues) highlighting any content you’d like us to provide but aren’t able to contribute yourself.
docs/css/access-nri.css:   ACCESS Hive CSS
docs/about/index.md:    The ACCESS Hive is a **documentation Hub** where the ACCESS Community can contribute documentation and other related material. 
docs/about/index.md:Contributions to the ACCESS Hive site are encouraged by any member of the community. Please refer to the [How to contribute guide][HCG] to learn how you can help the ACCESS community build a documentation database useful to all its members.
docs/about/index.md:You can also leave some comments and feedback about the ACCESS Hive content in the form of issues on [the ACCESS-Hive repository][IssueHive] or via email.    
docs/index.md:ACCESS Hive is a portal to all documentation pertinent to the Australian Community Climate & Earth System Simulator, ACCESS, and its model components.
mkdocs.yml:site_name: ACCESS Hive
mkdocs.yml:  - ACCESS Hive:
```

**Comment by aidanheerdegen** [comment]
- [ ] Add information on how to add tags to "how to contribute"

**Comment by ccarouge** [comment]
- [ ] change name of the organisation to ACCESS-Community

**Comment by KAUR1984** [comment]
Closing as seems to be referring to the old issue.
